version: "3.3"
services:
  app:
    build:
      context: .
    command: gunicorn --bind=0.0.0.0:5000 lb.journey_finder_flask.api:app
    ports:
      - "5000:5000"
    
  redis-local:
    image: redis