version: "3.3"
services:
  app:
    build:
      context: .
    command: gunicorn --bind=0.0.0.0:8000 lb.journey_finder_hug.api:__hug_wsgi__
    ports:
      - "8000:8000"

  redis-local:
    image: redis
